version = 0.1
[default.deploy.parameters]
stack_name = "patientjournal-rest-api"
resolve_s3 = true
s3_prefix = "patientjournal-rest-api"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
