AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
#Parameters:

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
  PatientJournalApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.patient_journal_rest_api.StreamLambdaHandler
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonRDSFullAccess
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
#          DB_ENDPOINT: !Ref DatabaseEndpoint
#          DB_PORT: !Ref DatabasePort
#          DB_NAME: !Ref DatabaseName
#          DB_USERNAME: !Ref DatabaseUsername
#          DB_PASSWORD: !Ref DatabasePassword
      Events:
        AllRoutes:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

Outputs:
  BackendApiUrl:
    Description: "URL of the backend API"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: PatientJournalBackendApiUrl

